import { expect, test } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
})

test('onboards, completes Day 1, and restores history after refresh', async ({ page }) => {
  await expect(page.getByRole('heading',{ name:/Build practical strength/ })).toBeVisible()
  await page.getByLabel('Dumbbell weights in pounds optional').fill('10, 15, 25')
  await page.getByRole('button',{ name:'Begin my challenge' }).click()
  await expect(page.getByRole('heading',{ name:'Starting point' })).toBeVisible()
  await page.getByRole('button',{ name:/readiness/i }).click()
  await page.getByRole('button',{ name:/Start Day 1 early|Start Normal session/ }).click()
  await expect(page.getByRole('heading',{ name:'Movement Primer' })).toBeVisible()
  await page.getByRole('button',{ name:/Start timer/ }).last().click()
  await page.getByRole('button',{ name:/Complete set/ }).click()
  await expect(page.getByRole('heading',{ name:'Incline Push-up' })).toBeVisible()
  for (let index=0;index<3;index+=1) await page.getByRole('button',{ name:/Complete set/ }).click()
  await page.getByRole('button',{ name:/Start timer/ }).last().click()
  await page.getByRole('button',{ name:/Finish/ }).click()
  await expect(page.getByRole('heading',{ name:'Today is in the books.' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading',{ name:'Today is in the books.' })).toBeVisible()
})

test('pain overrides the workout and the layout does not overflow a phone viewport', async ({ page }) => {
  await page.getByRole('button',{ name:'Begin my challenge' }).click()
  await page.getByRole('button',{ name:/readiness/i }).click()
  await expect(page.getByRole('dialog',{name:'How are you arriving?'})).toBeVisible()
  await page.getByRole('button',{ name:'present' }).click()
  await page.getByRole('button',{ name:/Start Day 1 early|View safety guidance/ }).click()
  await expect(page.getByRole('heading',{ name:'Stop and check the symptom.' })).toBeVisible()
  const dimensions=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}))
  expect(dimensions.scroll).toBeLessThanOrEqual(dimensions.client)
})

test('onboarding and Today have no automatically detectable WCAG A/AA violations', async ({ page }) => {
  const onboarding=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa']).analyze()
  expect(onboarding.violations).toEqual([])
  await page.getByRole('button',{ name:'Begin my challenge' }).click()
  const today=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa']).analyze()
  expect(today.violations).toEqual([])
  await page.getByRole('button',{name:/readiness/i}).click()
  await page.getByRole('button',{name:/Start Day 1 early|Start Normal session/}).click()
  const workout=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa']).analyze()
  expect(workout.violations).toEqual([])
})

test('restores an in-progress workout at the exact next exercise', async ({ page }) => {
  await page.getByRole('button',{name:'Begin my challenge'}).click()
  await page.getByRole('button',{name:/readiness/i}).click()
  await page.getByRole('button',{name:/Start Day 1 early|Start Normal session/}).click()
  await page.getByRole('button',{name:/Start timer/}).last().click()
  await page.getByRole('button',{name:/Complete set/}).click()
  await page.getByRole('button',{name:/Complete set/}).click()
  await expect(page.getByRole('heading',{name:'Goblet Squat'})).toBeVisible()
  await page.getByRole('button',{name:/Exit workout/}).click()
  await page.reload()
  await page.getByRole('button',{name:/readiness/i}).click()
  await page.getByRole('button',{name:/Start Day 1 early|Start Normal session/}).click()
  await expect(page.getByRole('heading',{name:'Goblet Squat'})).toBeVisible()
})

test('chooses dedicated minimum and recovery sessions from readiness', async ({ page }) => {
  await page.getByRole('button',{name:'Begin my challenge'}).click()
  await page.getByRole('button',{name:/readiness/i}).click()
  await page.getByRole('button',{name:'5 minutes'}).click()
  await expect(page.getByText('Five-minute minimum',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:/Start Day 1 early/}).click()
  await expect(page.getByRole('heading',{name:'Incline Push-up'})).toBeVisible()
  await page.getByRole('button',{name:/Exit workout/}).click()
  await page.getByRole('button',{name:/readiness/i}).click()
  await page.getByRole('button',{name:'5 minutes'}).click()
  await page.getByRole('button',{name:'significant'}).click()
  await expect(page.getByText('Recovery session',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:/Start Day 1 early/}).click()
  await expect(page.getByRole('heading',{name:'Reset Flow'})).toBeVisible()
})

test('finishes Day 90 with the same assessment setup and a continuation plan', async ({ page }) => {
  const date=new Date(); date.setDate(date.getDate()-89)
  const local=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`
  const profile={label:'My 90-Day Challenge',ageRange:'30–39',height:`5'9"`,weightLb:140,trainingHistory:'Formerly athletic; detrained',activityLevel:'Mostly sedentary',dumbbells:[10,15],limitations:'',preferredTime:'Morning',habitAnchor:'After coffee',hasSturdyChair:true,startDate:local,photoReminder:false,onboardingComplete:true}
  const assessments=[['incline-pushup',8,0,'Incline push-up'],['goblet-squat',10,10,'Goblet squat'],['one-arm-row',10,10,'Supported dumbbell row'],['side-plank',20,0,'Full side plank']].map(([exerciseId,value,weight,variation],index)=>({id:`a${index}`,date:local,day:1,metric:exerciseId==='side-plank'?'clean hold':'clean repetitions',value:Number(value),unit:exerciseId==='side-plank'?'seconds':'reps',exerciseId:String(exerciseId),weight:Number(weight)||undefined,variation:String(variation)}))
  const fixture=JSON.stringify({version:1,profile,sessions:[],assessments,bodyWeights:[{date:local,weightLb:140}],lastOpenedDate:local})
  await page.addInitScript((serialized)=>localStorage.setItem('ten-strong-data-v1',serialized),fixture)
  await page.goto('/?day90=1#/today')
  await expect(page.getByRole('heading',{name:'90-day check-in'})).toBeVisible()
  await page.getByRole('button',{name:/Check readiness/}).click()
  await page.getByRole('button',{name:/Start Normal session/}).click()
  await page.getByRole('button',{name:/Start timer/}).last().click()
  await page.getByRole('button',{name:/Complete set/}).click()
  await expect(page.getByText(/Repeat the Day 1 setup exactly/)).toBeVisible()
  for(let index=0;index<3;index+=1) await page.getByRole('button',{name:/Complete set/}).click()
  await page.getByRole('button',{name:/Start timer/}).last().click()
  await page.getByRole('button',{name:/Finish/}).click()
  await expect(page.getByRole('heading',{name:'You finished Ten Strong.'})).toBeVisible()
  await expect(page.getByRole('heading',{name:'Keep the ten-minute anchor.'})).toBeVisible()
})
