import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { BookOpen, ChevronRight, ClipboardList, Database, Download, Dumbbell, FileText, HeartPulse, RotateCcw, Scale, Settings, Upload } from 'lucide-react'
import { useAppState } from '../AppState'
import { exercises, exerciseById } from '../data/exercises'
import { fullProgram, phases, templateById } from '../data/program'
import { designPrinciples, sources } from '../data/methodology'
import { consistencyRate, getChallengeDay, totalMinutes } from '../lib/engine'
import { appDataSchema, clearData, downloadFile, parseImport, sessionsToCsv, summaryToHtml } from '../lib/storage'
import { ExerciseVisual } from '../components/ExerciseVisual'
import { formatISODate } from '../lib/date'

export function CalendarPage() {
  const {data}=useAppState(); const current=getChallengeDay(data.profile.startDate); const byDay=new Map(data.sessions.map(s=>[s.day,s]));
  return <div className="page"><div className="eyebrow">The whole arc</div><h1>90-day calendar</h1><p className="lede small">A missed day stays in the past. Today never contains make-up work.</p>{phases.map(phase=><section className="calendar-phase" key={phase.id}><div><span>Phase {phase.id}</span><h2>{phase.name}</h2></div><div className="day-grid">{fullProgram.filter(d=>d.phaseId===phase.id).map(day=>{const log=byDay.get(day.day);const status=log?.status??(day.day<current?'missed':day.day===current?'today':'upcoming');return <div className={`day-cell ${status} ${day.kind}`} aria-label={`Day ${day.day}, ${day.title}, ${status}`} key={day.day}><strong>{day.day}</strong><span>{status==='completed'?'✓':status==='recovery'?'○':status==='partial'?'½':status==='missed'?'—':status==='today'?'•':day.kind==='assessment'?'A':''}</span></div>})}</div></section>)}</div>
}

export function ProgressPage() {
  const {data,addBodyWeight}=useAppState()
  const [weightInput,setWeightInput]=useState(String(data.bodyWeights.at(-1)?.weightLb??data.profile.weightLb))
  const [weightMessage,setWeightMessage]=useState('')
  const rate=consistencyRate(data)
  const minutes=totalMinutes(data)
  const chart=useMemo(()=>data.sessions.slice(-12).map(s=>({day:`D${s.day}`,minutes:Math.max(1,Math.round(s.durationSeconds/60))})),[data.sessions])
  const chartMax=Math.max(12,...chart.map(point=>point.minutes))
  const exerciseStats=useMemo(()=>{
    const map=new Map<string,{name:string;first:number;latest:number;unit:string}>()
    data.sessions.forEach(session=>session.sets.filter(s=>s.completed).forEach(set=>{
      const value=set.reps??set.seconds??0
      const prev=map.get(set.exerciseId)
      map.set(set.exerciseId,{name:exerciseById[set.exerciseId]?.name??set.exerciseId,first:prev?.first??value,latest:Math.max(prev?.latest??0,value),unit:set.reps!==undefined?'reps':'sec'})
    }))
    return [...map.values()].slice(0,5)
  },[data.sessions])
  const assessmentComparisons=useMemo(()=>{
    const exerciseIds=[...new Set(data.assessments.map((result)=>result.exerciseId).filter(Boolean))] as string[]
    return exerciseIds.map((exerciseId)=>{
      const results=data.assessments.filter((result)=>result.exerciseId===exerciseId).sort((a,b)=>a.day-b.day)
      const baseline=results.find((result)=>result.day===1)
      const latest=results.at(-1)
      const comparable=Boolean(baseline&&latest&&baseline.id!==latest.id&&(baseline.weight??0)===(latest.weight??0)&&(baseline.variation??'')===(latest.variation??''))
      const change=baseline&&latest?latest.value-baseline.value:0
      return {exerciseId,name:exerciseById[exerciseId]?.name??exerciseId,baseline,latest,comparable,change,percentage:comparable&&baseline&&baseline.value>0?Math.round(change/baseline.value*100):null}
    })
  },[data.assessments])
  const bodyWeightMin=Math.min(...data.bodyWeights.map((entry)=>entry.weightLb),data.profile.weightLb)-1
  const bodyWeightMax=Math.max(...data.bodyWeights.map((entry)=>entry.weightLb),data.profile.weightLb)+1
  function logWeight(){const value=Number(weightInput);if(!Number.isFinite(value)||value<80||value>500){setWeightMessage('Enter a body weight between 80 and 500 lb.');return}addBodyWeight({date:formatISODate(new Date()),weightLb:value});setWeightMessage('Saved for today.')}
  return <div className="page">
    <div className="eyebrow">Evidence of practice</div><h1>Progress</h1>
    <div className="metric-grid"><article><strong>{rate}%</strong><span>consistency</span></article><article><strong>{data.sessions.length}</strong><span>days practiced</span></article><article><strong>{minutes}</strong><span>training minutes</span></article></div>
    <section className="card chart-card"><div><h2>Training rhythm</h2><p>Actual minutes from your latest sessions</p></div>{chart.length?<><div className="spark-bars" aria-hidden="true">{chart.map(point=><div className="spark-column" key={point.day}><span style={{height:`${Math.max(8,point.minutes/chartMax*100)}%`}}/><small>{point.day}</small></div>)}</div><table className="sr-only"><caption>Training minutes by session</caption><tbody>{chart.map(d=><tr key={d.day}><th>{d.day}</th><td>{d.minutes} minutes</td></tr>)}</tbody></table></>:<div className="empty-state">Complete your first session to start the chart.</div>}</section>
    <section><div className="section-heading"><div><div className="eyebrow">Comparable work</div><h2>Exercise bests</h2></div></div><div className="trend-list">{exerciseStats.length?exerciseStats.map(stat=>{const change=stat.latest-stat.first;const percentage=stat.first>0?Math.round(change/stat.first*100):null;return <div className="trend-row" key={stat.name}><div><strong>{stat.name}</strong><span>Start: {stat.first} {stat.unit} · Latest best: {stat.latest} {stat.unit}</span></div><div><strong>{change>=0?'+':''}{change}</strong><span>{percentage===null?'No % baseline':`${percentage>=0?'+':''}${percentage}%`}</span></div></div>}):<p className="empty-state">Your clean repetitions and timed holds will appear here.</p>}</div><p className="micro">Early strength changes can reflect renewed coordination, technique, and neural adaptation as well as muscle growth. Rep comparisons are most meaningful when load, variation, range, and tempo match.</p></section>
    {assessmentComparisons.length>0&&<section><div className="section-heading"><div><div className="eyebrow">Day 1 → final</div><h2>Assessment changes</h2></div></div><div className="trend-list">{assessmentComparisons.map(result=><div className="trend-row" key={result.exerciseId}><div><strong>{result.name}</strong><span>{result.baseline?`Start: ${result.baseline.value} ${result.baseline.unit}`:'No Day 1 baseline'}{result.latest&&result.latest.id!==result.baseline?.id?` · Latest: ${result.latest.value} ${result.latest.unit}`:''}</span></div><div>{result.comparable?<><strong>{result.change>=0?'+':''}{result.change}</strong><span>{result.percentage!==null?`${result.percentage>=0?'+':''}${result.percentage}%`:'No percentage'}</span></>:<span>Awaiting same-setup final</span>}</div></div>)}</div></section>}
    <section className="card weight-card"><Scale/><div><h2>Optional body weight</h2><p>One to three entries per week is plenty. Daily fluctuations are normal.</p><div className="inline-entry"><input aria-label="Body weight in pounds" type="number" min="80" max="500" step="0.1" value={weightInput} onChange={(event)=>setWeightInput(event.target.value)}/><button className="button secondary" onClick={logWeight}>Save today</button></div>{weightMessage&&<small role="status">{weightMessage}</small>}{data.bodyWeights.length>1&&<><div className="weight-spark" aria-hidden="true">{data.bodyWeights.slice(-12).map((entry)=><span key={entry.date} style={{height:`${20+((entry.weightLb-bodyWeightMin)/(bodyWeightMax-bodyWeightMin))*70}%`}} title={`${entry.date}: ${entry.weightLb} lb`}/>)}</div><table className="sr-only"><caption>Body weight entries</caption><tbody>{data.bodyWeights.map(entry=><tr key={entry.date}><th>{entry.date}</th><td>{entry.weightLb} lb</td></tr>)}</tbody></table></>}</div></section>
  </div>
}

export function ExerciseLibraryPage(){const [filter,setFilter]=useState('all');const visible=filter==='all'?exercises:exercises.filter(e=>e.pattern===filter);return <div className="page"><div className="eyebrow">Movement before load</div><h1>Exercise library</h1><div className="filter-row"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>All</button>{['push','pull','squat','hinge','unilateral','trunk','carry','recovery'].map(p=><button className={filter===p?'active':''} onClick={()=>setFilter(p)} key={p}>{p}</button>)}</div><div className="exercise-grid">{visible.map(exercise=><article className="exercise-card card" key={exercise.id}><ExerciseVisual exercise={exercise} compact/><span className="kind">{exercise.pattern}</span><h2>{exercise.name}</h2><ul>{exercise.cues.slice(0,3).map(c=><li key={c}>{c}</li>)}</ul><details><summary>Regressions, progressions & safety</summary><dl><dt>Beginner</dt><dd>{exercise.regression}</dd><dt>Standard</dt><dd>{exercise.standard}</dd><dt>Progression</dt><dd>{exercise.progression}</dd><dt>No equipment</dt><dd>{exercise.noEquipment}</dd><dt>Common mistakes</dt><dd>{exercise.mistakes.join(' · ')}</dd></dl><p className="warning">{exercise.warning}</p></details></article>)}</div></div>}

export function PlanPage(){const current=getChallengeDay(useAppState().data.profile.startDate);return <div className="page"><div className="eyebrow">Ambitious, not reckless</div><h1>Your plan</h1><p className="lede small">Five progressive phases, alternating strength and recovery so each ten-minute session has a job.</p><div className="timeline">{phases.map(phase=><section className={`phase-card ${current>=phase.start&&current<=phase.end?'current':''}`} key={phase.id}><div className="phase-number">{phase.id}</div><div><span>Days {phase.start}–{phase.end}</span><h2>{phase.name}</h2><p>{phase.intent}</p><small>{phase.effort}</small></div></section>)}</div><section className="card week-card"><h2>A normal week covers</h2><div className="coverage"><span>Horizontal push</span><span>Vertical push</span><span>Horizontal pull</span><span>Squat</span><span>Hinge</span><span>Unilateral legs</span><span>Trunk</span><span>Carry</span></div><p>Recovery days are part of the prescription. They are not failed workouts.</p></section><section><div className="section-heading"><div><div className="eyebrow">Ahead, not overloaded</div><h2>Next seven days</h2></div></div>{fullProgram.filter(day=>day.day>=current&&day.day<current+7).map(day=><div className="plan-row" key={day.day}><span>Day {day.day}</span><div><strong>{templateById[day.templateId].title}</strong><small>{templateById[day.templateId].focus}</small></div><span className={`kind ${day.kind}`}>{day.kind}</span></div>)}</section></div>}

export function MethodologyPage(){return <div className="page article-page"><div className="eyebrow">How this plan was designed</div><h1>Useful evidence,<br/>translated into ten minutes.</h1><p className="lede">Ten Strong is an educational program for a detrained adult—not a medical service, maximal-strength protocol, or promise of a particular physique.</p><div className="principle-grid">{designPrinciples.map((p,i)=><article key={p.title}><span>0{i+1}</span><h2>{p.title}</h2><p>{p.text}</p></article>)}</div><section><h2>The honest constraint</h2><p>Ten minutes per day cannot simultaneously maximize strength, muscle gain, conditioning, and mobility. Most studies use longer sessions, so this plan extrapolates by distributing a modest weekly training dose across short sessions. It emphasizes practical strength, movement quality, and adherence.</p><p>Reps in reserve are self-reported and imprecise at first. Home dumbbell jumps may also be larger than ideal. The app uses transparent rules rather than pretending those limits do not exist.</p></section><section><h2>Recovery & food, kept practical</h2><p>At roughly 140 lb (63.5 kg), a flexible daily protein range around <strong>80–105 g</strong> is reasonable for a healthy adult training for strength. In ordinary terms: include a palm-sized protein food at three or four meals. If you have kidney disease, a prescribed diet, or related medical concerns, discuss protein intake with a clinician.</p><div className="guidance-grid"><div><strong>Sleep</strong><span>A consistent window and at least seven hours when possible.</span></div><div><strong>Walking</strong><span>An optional easy 10–20 minutes, accumulated any way you like.</span></div><div><strong>Hydration</strong><span>Drink to thirst, keep water nearby, and increase fluids in heat.</span></div><div><strong>Food</strong><span>No calorie counting required. Eat enough to support stable energy and recovery.</span></div></div></section><section><h2>Sources</h2><ol className="sources">{sources.map(source=><li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a><p>{source.note}</p></li>)}</ol></section></div>}

export function MorePage(){return <div className="page"><div className="eyebrow">Reference & control</div><h1>More</h1><div className="menu-list"><Link to="/plan"><ClipboardList/><div><strong>Plan</strong><span>Phases, weekly rhythm, and what’s ahead</span></div><ChevronRight/></Link><Link to="/exercises"><Dumbbell/><div><strong>Exercise library</strong><span>Cues, regressions, and substitutions</span></div><ChevronRight/></Link><Link to="/recovery"><HeartPulse/><div><strong>Recovery guide</strong><span>Sleep, walking, food, soreness, and stress</span></div><ChevronRight/></Link><Link to="/methodology"><BookOpen/><div><strong>Methodology</strong><span>Evidence, assumptions, and limitations</span></div><ChevronRight/></Link><Link to="/settings"><Settings/><div><strong>Settings & data</strong><span>Equipment, backup, restore, and reset</span></div><ChevronRight/></Link></div></div>}

export function RecoveryPage(){return <div className="page article-page"><div className="eyebrow">Adaptation happens between sessions</div><h1>Recovery, without turning life into a spreadsheet.</h1><div className="recovery-list"><article><span>01</span><div><h2>Protect a sleep window</h2><p>Aim for consistency and at least seven hours when possible. A poor night does not erase progress; choose reduced volume when energy is unusually low.</p></div></article><article><span>02</span><div><h2>Eat enough protein and total food</h2><p>For this starting profile, roughly 80–105 g of protein per day is a flexible range—not a pass/fail target. Add protein-containing food to each meal. Supplements are optional convenience.</p></div></article><article><span>03</span><div><h2>Walk because it helps, not as punishment</h2><p>An easy 10–20 minute daily walk can support health and recovery. Break it into smaller pieces if that fits better.</p></div></article><article><span>04</span><div><h2>Read soreness honestly</h2><p>Mild, improving muscular soreness can support a reduced session. Significant, worsening, or joint-centered pain calls for recovery and, when concerning, professional assessment.</p></div></article><article><span>05</span><div><h2>Alcohol and stress count</h2><p>Less alcohol generally supports sleep and recovery. High stress is a valid reason to reduce the training dose; there is no make-up work.</p></div></article></div></div>}

export function SettingsPage(){
  const {data,updateProfile,replaceData,resetData,restartChallenge}=useAppState()
  const [weights,setWeights]=useState(data.profile.dumbbells.join(', '))
  const [preferredTime,setPreferredTime]=useState(data.profile.preferredTime)
  const [habitAnchor,setHabitAnchor]=useState(data.profile.habitAnchor)
  const [hasSturdyChair,setHasSturdyChair]=useState(data.profile.hasSturdyChair)
  const [photoReminder,setPhotoReminder]=useState(data.profile.photoReminder)
  const [restartDate,setRestartDate]=useState(formatISODate(new Date()))
  const [message,setMessage]=useState('')
  function savePreferences(){updateProfile({dumbbells:[...new Set(weights.split(',').map(v=>Number(v.trim())).filter(v=>v>0))].sort((a,b)=>a-b),preferredTime,habitAnchor,hasSturdyChair,photoReminder});setMessage('Preferences saved. Future recommendations will use your equipment.')}
  async function importFile(file?:File){if(!file)return;if(file.size>2_000_000){setMessage('That file is too large. Ten Strong backups must be under 2 MB.');return}try{const parsed=parseImport(await file.text());replaceData(parsed);setWeights(parsed.profile.dumbbells.join(', '));setPreferredTime(parsed.profile.preferredTime);setHabitAnchor(parsed.profile.habitAnchor);setHasSturdyChair(parsed.profile.hasSturdyChair);setPhotoReminder(parsed.profile.photoReminder);setMessage(`Restored ${parsed.sessions.length} sessions from the backup.`)}catch(error){setMessage(error instanceof Error?error.message:'Import failed. Your existing data was not changed.')}}
  function reset(){if(!window.confirm('Reset this challenge and remove its local history? Export first if you want a backup.'))return;clearData();resetData();window.location.hash='#/onboarding'}
  function restart(){if(!window.confirm('Start a fresh 90-day challenge? Current workout history will be removed. Export it first if you want to keep it.'))return;restartChallenge(restartDate);window.location.hash='#/today'}
  return <div className="page"><div className="eyebrow">Local-first control</div><h1>Settings & data</h1>{message&&<div className="notice" role="status">{message}</div>}
    <section className="card settings-section"><Dumbbell/><div><h2>Training setup</h2><label>Dumbbell weights in pounds<input value={weights} onChange={e=>setWeights(e.target.value)} placeholder="10, 15, 25"/></label><div className="two-col"><label>Preferred time<select value={preferredTime} onChange={e=>setPreferredTime(e.target.value)}><option>Morning</option><option>Midday</option><option>Evening</option><option>Flexible</option></select></label><label>Habit anchor<input value={habitAnchor} onChange={e=>setHabitAnchor(e.target.value)}/></label></div><label className="check"><input type="checkbox" checked={hasSturdyChair} onChange={e=>setHasSturdyChair(e.target.checked)}/><span>I have a sturdy chair, couch, or counter for support.</span></label><label className="check"><input type="checkbox" checked={photoReminder} onChange={e=>setPhotoReminder(e.target.checked)}/><span>Show optional progress-photo reminders on Days 1 and 90.</span></label><button className="button secondary" onClick={savePreferences}>Save preferences</button></div></section>
    <section className="card settings-section"><Database/><div><h2>Backup and restore</h2><p>Personal data stays in this browser. Browser storage can be lost when site data is cleared, so export a backup weekly.</p><div className="button-stack"><button className="button secondary" onClick={()=>downloadFile('ten-strong-backup.json',JSON.stringify(data,null,2),'application/json')}><Download/> Export JSON backup</button><button className="button secondary" onClick={()=>downloadFile('ten-strong-summary.csv',sessionsToCsv(data),'text/csv')}><FileText/> Download CSV summary</button><button className="button secondary" onClick={()=>downloadFile('ten-strong-summary.html',summaryToHtml(data),'text/html')}><FileText/> Download printable summary</button><label className="button secondary file-button"><Upload/> Import JSON<input type="file" accept="application/json,.json" onChange={e=>importFile(e.target.files?.[0])}/></label></div></div></section>
    <section className="card install-section"><div className="app-icon">10</div><div><h2>Save to your iPhone</h2><ol><li>Open the deployed site in Safari.</li><li>Tap the Share button.</li><li>Choose <strong>Add to Home Screen</strong>.</li></ol><p>Open the installed app once while online. After that, the program and history work offline.</p></div></section>
    <section className="danger-zone"><h2>Start another 90 days</h2><p>Keep your profile and equipment but clear this challenge’s history.</p><div className="inline-entry"><input aria-label="New challenge start date" type="date" value={restartDate} onChange={e=>setRestartDate(e.target.value)}/><button className="button secondary" onClick={restart}>Restart challenge</button></div><h2>Reset everything</h2><p>Remove this app’s profile and challenge history from the browser.</p><button className="button danger" onClick={reset}><RotateCcw/> Reset everything</button></section><p className="micro">Schema version {appDataSchema.safeParse(data).success?'1 · valid':'unknown'} · No remote database · No analytics</p>
  </div>
}
